import { Hero } from './hero';
import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      { id: 12, name: 'Dr. Nice' },
      { id: 13, name: 'Bombasto' },
      { id: 14, name: 'Celeritas' },
      { id: 15, name: 'Magneta' },
      { id: 16, name: 'RubberMan' },
      { id: 17, name: 'Dynama' },
      { id: 18, name: 'Dr. IQ' },
      { id: 19, name: 'Magma' },
      { id: 20, name: 'Tornado' },
    ];

    const details = [
      { id: 12, backstory: 'Just too nice to be a vilain' },
      { id: 13, backstory: 'Played too much bomberman' },
      { id: 14, backstory: 'Fast and also a latin nerd' },
      { id: 15, backstory: 'Just Magneto with an A' },
      { id: 16, backstory: 'Ate a cursed Fruit' },
      { id: 17, backstory: 'Very dynamic' },
      { id: 18, backstory: 'Actualy average intelligence, but super strengh' },
      { id: 19, backstory: 'Fell in a volcano, idk what happened' },
      { id: 20, backstory: 'Hurricane was taken' },
    ];

    const peoplesaved = [
      {
        id: 1,
        name: 'Stearne',
        company: 'Corwin Group',
        savedby: 15,
        savedwhen: '03/31/2022',
      },
      {
        id: 2,
        name: 'Dannie',
        company: 'Gottlieb-Hessel',
        savedby: 19,
        savedwhen: '01/21/2022',
      },
      {
        id: 3,
        name: 'Kaja',
        company: 'Keebler LLC',
        savedby: 17,
        savedwhen: '05/27/2022',
      },
      {
        id: 4,
        name: 'Vernen',
        company: 'Wisoky LLC',
        savedby: 17,
        savedwhen: '11/22/2021',
      },
      {
        id: 5,
        name: 'Powell',
        company: 'Bogisich-Hammes',
        savedby: 15,
        savedwhen: '05/09/2022',
      },
      {
        id: 6,
        name: 'Claudian',
        company: 'Zboncak, Bergstrom and Quitzon',
        savedby: 20,
        savedwhen: '09/20/2022',
      },
      {
        id: 7,
        name: 'Jules',
        company: 'Reynolds and Sons',
        savedby: 16,
        savedwhen: '10/31/2022',
      },
      {
        id: 8,
        name: 'Kalie',
        company: 'Kilback-Heathcote',
        savedby: 13,
        savedwhen: '04/25/2022',
      },
      {
        id: 9,
        name: 'Sasha',
        company: 'Windler and Sons',
        savedby: 16,
        savedwhen: '11/13/2022',
      },
      {
        id: 10,
        name: 'Sibyl',
        company: 'Dibbert-Upton',
        savedby: 19,
        savedwhen: '09/15/2022',
      },
      {
        id: 11,
        name: 'Ibrahim',
        company: 'Little Inc',
        savedby: 18,
        savedwhen: '09/08/2022',
      },
      {
        id: 12,
        name: 'Raimund',
        company: 'Kutch Group',
        savedby: 19,
        savedwhen: '09/21/2022',
      },
      {
        id: 13,
        name: 'Chad',
        company: 'Orn and Sons',
        savedby: 16,
        savedwhen: '06/28/2022',
      },
      {
        id: 14,
        name: 'Tania',
        company: 'Prohaska LLC',
        savedby: 15,
        savedwhen: '04/20/2022',
      },
      {
        id: 15,
        name: 'Lynn',
        company: 'Johnson, Thompson and Swift',
        savedby: 15,
        savedwhen: '03/07/2022',
      },
      {
        id: 16,
        name: 'Caritta',
        company: 'Little LLC',
        savedby: 14,
        savedwhen: '11/15/2022',
      },
      {
        id: 17,
        name: 'Clim',
        company: 'Rice LLC',
        savedby: 20,
        savedwhen: '09/13/2022',
      },
      {
        id: 18,
        name: 'Barry',
        company: 'Kulas-Kovacek',
        savedby: 18,
        savedwhen: '11/30/2021',
      },
      {
        id: 19,
        name: 'Luca',
        company: 'Robel Group',
        savedby: 12,
        savedwhen: '04/26/2022',
      },
      {
        id: 20,
        name: 'Lorrie',
        company: 'Kuhic-Parker',
        savedby: 12,
        savedwhen: '04/16/2022',
      },
      {
        id: 21,
        name: 'Buck',
        company: 'McDermott-Gulgowski',
        savedby: 13,
        savedwhen: '09/24/2022',
      },
      {
        id: 22,
        name: 'Decca',
        company: 'Rempel, Ebert and Schumm',
        savedby: 16,
        savedwhen: '03/04/2022',
      },
      {
        id: 23,
        name: 'Jeannine',
        company: "O'Connell-Schmitt",
        savedby: 16,
        savedwhen: '10/09/2022',
      },
      {
        id: 24,
        name: 'Lani',
        company: 'Aufderhar-Lowe',
        savedby: 12,
        savedwhen: '09/15/2022',
      },
      {
        id: 25,
        name: 'Maximilian',
        company: 'Kiehn, Heller and Stamm',
        savedby: 19,
        savedwhen: '05/09/2022',
      },
      {
        id: 26,
        name: 'Chris',
        company: "Bauch, Thompson and O'Kon",
        savedby: 19,
        savedwhen: '09/26/2022',
      },
      {
        id: 27,
        name: 'Laraine',
        company: 'Murazik-Tillman',
        savedby: 20,
        savedwhen: '03/30/2022',
      },
      {
        id: 28,
        name: 'Robbyn',
        company: 'Heaney-Will',
        savedby: 12,
        savedwhen: '06/19/2022',
      },
      {
        id: 29,
        name: 'Ellene',
        company: 'Nader, Pacocha and Johnson',
        savedby: 14,
        savedwhen: '05/29/2022',
      },
      {
        id: 30,
        name: 'Shelley',
        company: 'Barrows-McKenzie',
        savedby: 12,
        savedwhen: '04/07/2022',
      },
      {
        id: 31,
        name: 'Bondie',
        company: 'Hodkiewicz-Rath',
        savedby: 20,
        savedwhen: '08/01/2022',
      },
      {
        id: 32,
        name: 'Agneta',
        company: 'Spencer and Sons',
        savedby: 18,
        savedwhen: '01/22/2022',
      },
      {
        id: 33,
        name: 'Linzy',
        company: 'Stanton-Senger',
        savedby: 16,
        savedwhen: '11/19/2021',
      },
      {
        id: 34,
        name: 'Jeremie',
        company: 'Franecki-Greenholt',
        savedby: 20,
        savedwhen: '04/12/2022',
      },
      {
        id: 35,
        name: 'Donnie',
        company: 'Stracke, Yost and Dibbert',
        savedby: 13,
        savedwhen: '12/20/2021',
      },
      {
        id: 36,
        name: 'Tracy',
        company: 'Boyer-Mertz',
        savedby: 17,
        savedwhen: '11/17/2021',
      },
      {
        id: 37,
        name: 'Johnath',
        company: 'Olson-Ryan',
        savedby: 12,
        savedwhen: '09/30/2022',
      },
      {
        id: 38,
        name: 'Germana',
        company: 'Schaefer, Schumm and Kerluke',
        savedby: 16,
        savedwhen: '11/19/2021',
      },
      {
        id: 39,
        name: 'Tallou',
        company: 'Schmeler, Crist and VonRueden',
        savedby: 17,
        savedwhen: '12/03/2021',
      },
      {
        id: 40,
        name: 'Holden',
        company: 'Smith-Senger',
        savedby: 18,
        savedwhen: '06/06/2022',
      },
      {
        id: 41,
        name: 'Christabel',
        company: 'Breitenberg, Ullrich and Ritchie',
        savedby: 12,
        savedwhen: '09/17/2022',
      },
      {
        id: 42,
        name: 'Larissa',
        company: 'Casper, Hamill and Cassin',
        savedby: 13,
        savedwhen: '04/11/2022',
      },
      {
        id: 43,
        name: 'Siffre',
        company: 'Block-Berge',
        savedby: 16,
        savedwhen: '11/25/2021',
      },
      {
        id: 44,
        name: 'Helenelizabeth',
        company: 'Feest-Hickle',
        savedby: 17,
        savedwhen: '05/29/2022',
      },
      {
        id: 45,
        name: 'Mendie',
        company: 'Kuhlman, Dooley and Lind',
        savedby: 12,
        savedwhen: '05/24/2022',
      },
      {
        id: 46,
        name: 'Duff',
        company: 'Fritsch-Hyatt',
        savedby: 12,
        savedwhen: '07/24/2022',
      },
      {
        id: 47,
        name: 'Richard',
        company: 'Nicolas-Kovacek',
        savedby: 14,
        savedwhen: '03/21/2022',
      },
      {
        id: 48,
        name: 'Bess',
        company: 'Dicki, Konopelski and Rodriguez',
        savedby: 14,
        savedwhen: '07/12/2022',
      },
      {
        id: 49,
        name: 'Zollie',
        company: 'Halvorson, Schmidt and Lind',
        savedby: 19,
        savedwhen: '09/08/2022',
      },
      {
        id: 50,
        name: 'Melissa',
        company: 'Harvey-Collier',
        savedby: 13,
        savedwhen: '10/03/2022',
      },
    ];
    return { heroes, details, peoplesaved };
  }

  genId(heroes: Hero[]): number {
    return heroes.length > 0
      ? Math.max(...heroes.map((hero) => hero.id)) + 1
      : 11;
  }
}
